// Generated by CoffeeScript 1.10.0
(function() {
  var authenticate, authorize, confirm, delete_, get, identify, issue_token, register, util, verify;

  authenticate = require('./cmd/authenticate');

  authorize = require('./cmd/authorize');

  identify = require('./cmd/identify');

  confirm = require('./cmd/confirm');

  verify = require('./cmd/verify');

  get = require('./cmd/get');

  issue_token = require('./cmd/issue_token');

  register = require('./cmd/register');

  delete_ = require('./cmd/delete');

  util = require('./util');

  module.exports = function(options) {
    var role, seneca;
    seneca = this;
    role = 'account';
    seneca.add("init:" + role, function(msg, respond) {
      var required;
      required = ['registration.starter_status', 'token.secret', 'authorization.acl'];
      util.check_options(options, required);
      return respond();
    });
    seneca.add("role:" + role + ",cmd:authenticate", authenticate(seneca));
    seneca.add("role:" + role + ",cmd:authorize", authorize(seneca, options.authorization));
    seneca.add("role:" + role + ",cmd:identify", identify(seneca));
    seneca.add("role:" + role + ",cmd:confirm", confirm(seneca));
    seneca.add("role:" + role + ",cmd:verify", verify(seneca, options.token));
    seneca.add("role:" + role + ",cmd:get", get(seneca));
    seneca.add("role:" + role + ",cmd:issue_token", issue_token(seneca, options.token));
    seneca.add("role:" + role + ",cmd:register", register(seneca, options.registration));
    seneca.add("role:" + role + ",cmd:delete", delete_(seneca));
    return {
      name: role
    };
  };

}).call(this);

//# sourceMappingURL=plugin.js.map
