// Generated by CoffeeScript 1.10.0
(function() {
  var _, bcrypt;

  bcrypt = require('bcryptjs');

  _ = require('lodash');

  module.exports = function(seneca, options) {
    var cmd_authenticate;
    cmd_authenticate = function(params, respond) {
      var email, password, response;
      email = params.email.toLowerCase();
      password = params.password;
      response = {
        authenticated: false
      };
      if (email && password) {
        return seneca.act('role:account,cmd:identify', {
          email: email
        }, function(error, account) {
          if (account) {
            seneca.log.debug('account identified', account.id);
            return bcrypt.compare(password, account.hash, function(error, passed) {
              if (error) {
                seneca.log.error('password check failed:', error.message);
                return respond(null, response);
              } else {
                seneca.log.debug('password check returned', passed);
                response.authenticated = passed;
                if (passed) {
                  _.merge(response, account);
                }
                return respond(null, response);
              }
            });
          } else {
            seneca.log.debug('authentication failed, unidentified account', email);
            response.identified = false;
            return respond(null, response);
          }
        });
      } else {
        seneca.log.error('missing account_id or password', email, password);
        return respond(null, response);
      }
    };
    return cmd_authenticate;
  };

}).call(this);

//# sourceMappingURL=authenticate.js.map
