// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(seneca, options) {
    var acl, cmd_authorize;
    acl = options.acl;
    cmd_authorize = function(args, respond) {
      var account, action, resource, response, token;
      resource = args.resource;
      action = args.action;
      token = args.token;
      account = seneca.pin({
        role: 'account',
        cmd: '*'
      });
      response = {
        authorized: false
      };
      return account.verify({
        token: token
      }, function(error, res) {
        var account_id;
        if (error || !res.decoded) {
          return respond(null, response);
        }
        account_id = res.decoded.id;
        if (!account_id) {
          seneca.log.error('failed to decode id');
          return respond(null, response);
        }
        return account.get({
          account_id: account_id
        }, function(error, account) {
          if (account) {
            seneca.log.debug('checking access', account.id, resource, action);
            return acl.addUserRoles(account_id, [account.status], function(error) {
              if (error) {
                seneca.log.error('adding role to account failed:', error.message);
                return respond(error, null);
              }
              return acl.isAllowed(account_id, resource, action, function(error, res) {
                if (error) {
                  seneca.log.error('access check failed', error);
                  return respond(null, response);
                } else {
                  response.authorized = res;
                  return respond(null, response);
                }
              });
            });
          } else {
            seneca.log.debug('authorization failed, unidentified account', account_id);
            return respond(null, response);
          }
        });
      });
    };
    return cmd_authorize;
  };

}).call(this);

//# sourceMappingURL=authorize.js.map
