// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(seneca, options) {
    var cmd_confirm;
    cmd_confirm = function(args, respond) {
      var account, conf_token;
      conf_token = args.token;
      account = seneca.pin({
        role: 'account',
        cmd: '*'
      });
      return account.verify({
        token: conf_token
      }, function(error, res) {
        var account_records;
        if (error || !res.decoded || res.decoded.reason !== 'conf') {
          return respond(null, {
            message: 'token verification error'
          });
        }
        account_records = seneca.make('account');
        return account_records.load$(res.decoded.id, function(error, acc) {
          if (error) {
            seneca.log.error('error while loading account', decoded.id, error.message);
            return respond(null, null);
          } else {
            acc.status = 'confirmed';
            return acc.save$(function(error, saved_acc) {
              if (error) {
                seneca.log.error('account record update failed:', error.message);
                return respond(error, null);
              }
              if (saved_acc) {
                return respond(null, saved_acc);
              }
            });
          }
        });
      });
    };
    return cmd_confirm;
  };

}).call(this);

//# sourceMappingURL=confirm.js.map
