// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(seneca, options) {
    var cmd_delete;
    cmd_delete = function(msg, respond) {
      var account_records, id;
      id = msg.email;
      account_records = seneca.make('account');
      return account_records.remove$(id, function(error) {
        if (error) {
          seneca.log.error('error while deleting account', id, error.message);
          seneca.act('role:error,cmd:register', {
            from: 'account.delete.entity.remove$',
            message: error.message,
            args: {
              id: id
            }
          });
        }
        return respond(error, null);
      });
    };
    return cmd_delete;
  };

}).call(this);

//# sourceMappingURL=delete.js.map
