// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(seneca, options) {
    var cmd_get;
    cmd_get = function(args, respond) {
      var account_records, id;
      id = args.account_id;
      account_records = seneca.make('account');
      return account_records.load$(id, function(error, account) {
        if (error) {
          seneca.log.error('error while loading account', email, error.message);
          return respond(null, null);
        } else {
          return respond(null, account);
        }
      });
    };
    return cmd_get;
  };

}).call(this);

//# sourceMappingURL=get.js.map
