// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(seneca, options) {
    var cmd_identify;
    cmd_identify = function(args, respond) {
      var account_records, email;
      email = args.email;
      account_records = seneca.make(options.zone, options.base, 'account');
      return account_records.list$({
        email: email
      }, function(error, accounts) {
        if (error) {
          seneca.log.error('error while loading account', email, error.message);
          return respond(null, null);
        } else {
          return respond(null, accounts[0]);
        }
      });
    };
    return cmd_identify;
  };

}).call(this);

//# sourceMappingURL=identify.js.map
