// Generated by CoffeeScript 1.10.0
(function() {
  var _, jwt;

  jwt = require('jsonwebtoken');

  _ = require('lodash');

  module.exports = function(seneca, options) {
    var cmd_issue_token;
    cmd_issue_token = function(args, respond) {
      var account_id, custom_payload, payload, reason, res, secret;
      account_id = args.account_id;
      custom_payload = args.payload;
      reason = args.reason || 'auth';
      payload = {
        id: account_id,
        reason: reason
      };
      res = {};
      secret = options.secret;
      _.merge(payload, custom_payload);
      seneca.log.debug('signing payload:', payload);
      res.token = jwt.sign(payload, secret, {
        noTimestamp: options.jwtNoTimestamp
      });
      return respond(null, res);
    };
    return cmd_issue_token;
  };

}).call(this);

//# sourceMappingURL=issue_token.js.map
