// Generated by CoffeeScript 1.10.0
(function() {
  var jwt;

  jwt = require('jsonwebtoken');

  module.exports = function(seneca, options) {
    var cmd_issue_token;
    cmd_issue_token = function(params, respond) {
      var account_id, res, secret;
      account_id = params.email;
      res = {};
      secret = options.token_secret;
      res.token = jwt.sign({
        id: account_id
      }, secret, {
        noTimestamp: options.jwtNoTimestamp
      });
      return respond(null, res);
    };
    return cmd_issue_token;
  };

}).call(this);

//# sourceMappingURL=issue_token.js.map
