// Generated by CoffeeScript 1.12.1
(function() {
  module.exports = function(seneca, options) {
    var cmd_list;
    cmd_list = function(args, respond) {
      var account_records, limit, skip;
      skip = args.skip;
      limit = args.limit;
      seneca.log.debug('getting list of accounts');
      account_records = seneca.make(options.zone, options.base, 'account');
      return account_records.list$({
        skip$: skip,
        limit$: limit
      }, function(error, accounts) {
        if (error) {
          seneca.log.error('error while loading accounts:', error.message);
          return respond(error, null);
        } else {
          return respond(null, accounts);
        }
      });
    };
    return cmd_list;
  };

}).call(this);
