// Generated by CoffeeScript 1.12.2
(function() {
  exports.cmd_list = function(seneca, options) {
    var cmd_list;
    cmd_list = function(args, respond) {
      var account_records, criteria, limit, query, skip;
      criteria = args.criteria;
      skip = args.skip;
      limit = args.limit;
      seneca.log.debug('getting list of accounts');
      account_records = seneca.make(options.zone, options.base, 'account');
      query = {};
      if (skip) {
        query.skip$ = skip;
      }
      if (limit) {
        query.limit$ = limit;
      }
      if (criteria && criteria.email) {
        query.email = criteria.email;
      }
      return account_records.list$(query, function(error, accounts) {
        if (error) {
          seneca.log.error('error while loading accounts:', error.message);
          return respond(error, null);
        } else {
          return respond(null, accounts);
        }
      });
    };
    return cmd_list;
  };

  exports.cmd_count = function(seneca, options) {
    var cmd_count;
    cmd_count = function(args, respond) {
      var account_records;
      seneca.log.debug('getting amount of accounts');
      account_records = seneca.make(options.zone, options.base, 'account');
      return account_records.list$(function(error, accounts) {
        if (error) {
          seneca.log.error('error while loading accounts:', error.message);
          return respond(error, null);
        } else {
          return respond(null, {
            number: accounts.length
          });
        }
      });
    };
    return cmd_count;
  };

}).call(this);
