// Generated by CoffeeScript 1.10.0
(function() {
  var jwt;

  jwt = require('jsonwebtoken');

  module.exports = function(seneca, options) {
    var cmd_login;
    cmd_login = function(params, respond) {
      var account_id, password;
      account_id = params.account_id;
      password = params.password;
      return seneca.act('role:account,cmd:authenticate', {
        account_id: account_id,
        password: password
      }, function(error, res) {
        var secret;
        if (res && res.authenticated) {
          secret = options.secret;
          res.token = jwt.sign({
            id: account_id
          }, secret, {
            noTimestamp: options.jwtNoTimestamp
          });
          return respond(null, res);
        } else {
          return respond(null, res);
        }
      });
    };
    return cmd_login;
  };

}).call(this);

//# sourceMappingURL=login.js.map
