// Generated by CoffeeScript 1.10.0
(function() {
  var profile;

  profile = function(options) {
    var plugin, seneca;
    seneca = this;
    plugin = 'profile';
    seneca.add("plugin:" + plugin + ",action:get", function(params, respond) {
      var account_id, storage;
      account_id = params.account_id;
      storage = seneca.make(plugin);
      return storage.load$(account_id, function(error, profile) {
        return respond(error, profile);
      });
    });
    return seneca.add("plugin:" + plugin + ",action:update", function(params, respond) {
      var account_id, data;
      data = params.data;
      account_id = params.account_id;
      return seneca.act("plugin:" + plugin + ",action:get", {
        account_id: account_id
      }, function(error, profile) {
        if (!profile) {
          seneca.log.debug('failed to load existing profile for ', account_id);
          seneca.log.debug('creating new profile record for ', account_id);
          data.id = account_id;
          return seneca.make(plugin).data$(data).save$(function(error, profile) {
            seneca.log.debug('new profile saved for ', account_id);
            return respond(error, profile);
          });
        } else {
          return profile.data$(data).save$(function(error, profile) {
            seneca.log.debug('profile updated for ', account_id);
            return respond(error, profile);
          });
        }
      });
    });
  };

  module.exports = profile;

}).call(this);

//# sourceMappingURL=profile.js.map
