// Generated by CoffeeScript 1.10.0
(function() {
  var bcrypt, moment, util, validator;

  bcrypt = require('bcryptjs');

  validator = require('validator');

  moment = require('moment');

  util = require('./../util');

  module.exports = function(seneca, options) {
    var account, acl, cmd_register, password_generated, password_length, starter_role;
    acl = options.acl;
    starter_role = options.starter_role;
    password_length = options.password_length || 8;
    password_generated = false;
    account = seneca.pin({
      role: 'account',
      cmd: '*'
    });
    cmd_register = function(args, respond) {
      var email;
      email = args.email;
      if (!validator.isEmail(email)) {
        seneca.log.warn('bad email', email);
        return respond(null, null);
      }
      return account.identify({
        email: email
      }, function(error, account) {
        var password;
        if (account) {
          seneca.log.warn('account already registered', account.email);
          return respond(null, null);
        } else {
          password = args.password;
          if (!password) {
            seneca.log.debug('generating password');
            password = util.generate_password(password_length);
            password_generated = true;
          }
          return bcrypt.genSalt(10, function(error, salt) {
            if (error) {
              seneca.log.error('salt generation failed:', error.message);
              return respond(error, null);
            }
            return bcrypt.hash(password, salt, function(error, hash) {
              if (error) {
                seneca.log.error('password hash failed:', error.message);
                return respond(error, null);
              }
              seneca.log.debug('assigning starter role', starter_role);
              return acl.addUserRoles(email, [starter_role], function(error) {
                var new_account;
                if (error) {
                  seneca.log.error('adding starter role to new account failed:', error.message);
                  return respond(error, null);
                } else {
                  new_account = seneca.make('account');
                  new_account.email = email;
                  new_account.hash = hash;
                  new_account.registered_at = moment().format();
                  return new_account.save$(function(error, saved_account) {
                    if (error) {
                      seneca.log.error('new account record failed:', error.message);
                      respond(error, null);
                    }
                    if (saved_account) {
                      if (password_generated) {
                        saved_account.password = password;
                      }
                      return respond(null, saved_account);
                    }
                  });
                }
              });
            });
          });
        }
      });
    };
    return cmd_register;
  };

}).call(this);

//# sourceMappingURL=register.js.map
