// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(seneca, options) {
    var cmd_update;
    cmd_update = function(args, respond) {
      var account, account_id, account_records, new_status;
      account = seneca.pin({
        role: 'account',
        cmd: '*'
      });
      new_status = args.status;
      account_id = args.account_id;
      account_records = seneca.make('account');
      return account_records.load$(account_id, function(error, acc) {
        if (error) {
          seneca.log.error('error while loading account', account_id, error.message);
          return respond(error);
        } else {
          acc.status = new_status;
          return acc.save$(function(error, saved_acc) {
            if (error) {
              seneca.log.error('account record update failed:', error.message);
              return respond(error, null);
            }
            if (saved_acc) {
              return respond(null, saved_acc);
            }
          });
        }
      });
    };
    return cmd_update;
  };

}).call(this);

//# sourceMappingURL=update.js.map
