// Generated by CoffeeScript 1.10.0
(function() {
  var jwt;

  jwt = require('jsonwebtoken');

  module.exports = function(seneca, options) {
    var cmd_verify;
    cmd_verify = function(args, respond) {
      var response, secret, token;
      token = args.token;
      secret = options.secret;
      response = {
        token_verified: false
      };
      return jwt.verify(token, secret, function(error, decoded) {
        if (error) {
          seneca.log.debug('token verification error', error.message);
          return respond(null, response);
        }
        seneca.log.debug('token verified');
        response.token_verified = true;
        response.decoded = decoded;
        return respond(null, response);
      });
    };
    return cmd_verify;
  };

}).call(this);

//# sourceMappingURL=verify.js.map
